- menu_name: ""

#- name: "Tor"
#  url: "http:/tor.com"
#  title: "Tor"
  
#- name: "Brandon Sanderson"
#  url: "http:/brandonsanderson.com"
#  title: "Fantasy Author"

#- name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"

#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"

#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  title: "Sitemap for Google Webmaster Tools"
